version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - export NODE_OPTIONS=--openssl-legacy-provider
      - npm ci
  build:
    commands:
      - npm run build
      - npm run format
      - npm start
      - npm test
artifacts:
  files:
    - '**/*'
