version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - export NODE_OPTIONS=--openssl-legacy-provider
      - npm ci
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - sudo apt-get update -y
      - sudo apt-get install -y nginx
      - sudo cp ./public/index.html /usr/share/nginx/html/index.html
      - sudo systemctl restart ngnix
artifacts:
  files:
    - '**/*'
