version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - npm ci
  build:
    commands:
      - npm run build
      - npm run format
      - npm start
      - npm test
artifacts:
  files:
    - '**/*'
